# Generated by Django 5.2.6 on 2025-11-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=100)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
                ('author_role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
